language: php
php:
  - "5.3.3"
  - "5.4"
  - "5.5"

before_install:
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=bin\

install:
  - composer install

script: ./vendor/bin/phpunit